# Generated by Django 3.2.5 on 2021-11-11 22:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_class', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('grade_class',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('location',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('dob', models.DateField(default='2007-12-31')),
                ('house_no', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZW')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ZW')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gradeclass')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.location')),
            ],
            options={
                'ordering': ('grade_class', 'sex', 'surname'),
            },
        ),
    ]
